---
- name: "Load a variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- name: "Fetch artifact with {{ transport }} transport"
  include_tasks: "{{ transport_driver }}"
  with_first_found:
    - "transport/{{ transport }}.yml"
    - "transport/unknow-transport.yml"
  loop_control:
    loop_var: transport_driver

- name: "Choose platform {{ ansible_os_family }} based task"
  include_tasks: "{{ platform }}"
  with_first_found:
    - "system/{{ ansible_os_family }}.yml"
    - "system/not-supported.yml"
  loop_control:
    loop_var: platform
